version: "3.8"

services:
  metastore:
    image: postgres:15
    container_name: metastore
    hostname: metastore
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=iceberg
      - POSTGRES_PASSWORD=iceberg
      - POSTGRES_DB=metastore_db
    volumes:
      - metastore_data:/var/lib/postgresql/data
    networks:
      - spark-net

  spark-master:
    image: my-spark:3.5.6
    container_name: spark-master
    hostname: spark-master
    depends_on:
      - minio-init
    environment:
      - SPARK_MODE=master
      - HIVE_DB_PASSWORD=hive
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - spark-logs:/opt/spark/logs
      - ./spark-app:/opt/spark/app
    networks:
      - spark-net

  spark-worker-1:
    image: my-spark:3.5.6
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
      - minio-init
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    ports:
      - "9091:8080"
    volumes:
      - spark-logs:/opt/spark/logs
    networks:
      - spark-net

  spark-worker-2:
    image: my-spark:3.5.6
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
      - minio-init
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    ports:
      - "9092:8080"
    volumes:
      - spark-logs:/opt/spark/logs
    networks:
      - spark-net

  spark-history:
    image: my-spark:3.5.6
    container_name: spark-history
    hostname: spark-history
    depends_on:
      - minio-init
    environment:
      - SPARK_MODE=history
    ports:
      - "18080:18080"
    volumes:
      - spark-logs:/opt/spark/logs
    networks:
      - spark-net

  spark-submit:
    image: my-spark:3.5.6
    container_name: spark-submit
    depends_on:
      - spark-master
      - minio-init
    environment:
      - SPARK_MODE=client
    volumes:
      - ./spark-app:/opt/spark/app
      - spark-logs:/opt/spark/logs
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    networks:
      - spark-net

  minio:
    image: minio/minio:RELEASE.2024-05-28T17-19-04Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
      - ./minio/warehouse-policy.json:/etc/minio/warehouse-policy.json
    command: server /data --console-address ":9001"
    networks:
      - spark-net

  minio-init:
    image: minio/mc
    container_name: minio-init
    depends_on:
      - minio
    entrypoint: >
      bash -c "
        sleep 5 &&
        mc alias set local http://minio:9000 minioadmin minioadmin &&
        mc mb local/dlh || true &&
        mc admin user add local lakehouseuser lakehousepass || true &&
        mc admin policy create local dlh-policy /etc/minio/dlh-policy.json || true &&
        mc admin policy attach local dlh-policy --user lakehouseuser &&
        mc anonymous set download local/dlh
      "
    volumes:
      - ./minio/dlh-policy.json:/etc/minio/dlh-policy.json
    networks:
      - spark-net

volumes:
  spark-logs:
  minio_data:
  metastore_data:

networks:
  spark-net:
    driver: bridge