version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  app:
    build:
      context: ./app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: demo
      DB_USER: demo
      DB_PASS: demo
