version: "3.8"

x-worker-common: &worker-common
  image: my-spark:4.0.0
  depends_on:
    - spark-master
  environment:
    - SPARK_MODE=worker
    - SPARK_MASTER=spark://spark-master:7077
    - SPARK_WORKER_CORES=2
    - SPARK_WORKER_MEMORY=2g
  volumes:
    - spark-logs:/opt/spark/logs

services:
  spark-master:
    image: my-spark:4.0.0
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_DRIVER_MEMORY=512m
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark-app:/opt/spark/app
      - spark-logs:/opt/spark/logs

  spark-worker-1:
    <<: *worker-common
    container_name: spark-worker-1
    hostname: spark-worker-1
    ports:
      - "9091:8080"
      - "7001:7000"

  spark-worker-2:
    <<: *worker-common
    container_name: spark-worker-2
    hostname: spark-worker-2
    ports:
      - "9092:8080"
      - "7002:7000"

  history-server:
    image: my-spark:4.0.0
    container_name: spark-history
    hostname: spark-history
    ports:
      - "18080:18080"
    environment:
      - SPARK_MODE=history
    volumes:
      - spark-logs:/opt/spark/logs

  minio:
    image: minio/minio:latest
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio/data:/data

  mc:
    image: minio/mc
    container_name: minio-client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb -p local/spark-demo;
      mc anonymous set download local/spark-demo;
      tail -f /dev/null
      "

volumes:
  spark-logs:
