services:
  metastore_db:
    image: postgres:11
    hostname: metastore_db
    container_name: metastore_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    networks:
      - dlh-network

  hive-metastore:
    container_name: hive-metastore
    hostname: hive-metastore
    image: 'starburstdata/hive:3.1.2-e.15'
    ports:
      - '9083:9083' 
    environment:
      HIVE_METASTORE_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_JDBC_URL: jdbc:postgresql://metastore_db:5432/metastore
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hive
      HIVE_METASTORE_WAREHOUSE_DIR: s3://dlh/
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_PATH_STYLE_ACCESS: "true"
      REGION: ""
      GOOGLE_CLOUD_KEY_FILE_PATH: ""
      AZURE_ADL_CLIENT_ID: ""
      AZURE_ADL_CREDENTIAL: ""
      AZURE_ADL_REFRESH_URL: ""
      AZURE_ABFS_STORAGE_ACCOUNT: ""
      AZURE_ABFS_ACCESS_KEY: ""
      AZURE_WASB_STORAGE_ACCOUNT: ""
      AZURE_ABFS_OAUTH: ""
      AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
      AZURE_ABFS_OAUTH_CLIENT_ID: ""
      AZURE_ABFS_OAUTH_SECRET: ""
      AZURE_ABFS_OAUTH_ENDPOINT: ""
      AZURE_WASB_ACCESS_KEY: ""
    depends_on:
      - metastore_db
    networks:
      - dlh-network
  minio:
    hostname: minio
    image: minio/minio:RELEASE.2024-05-28T17-19-04Z
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
    networks:
      - dlh-network
  minio-init:
    image: minio/mc
    container_name: minio-init
    depends_on:
      - minio
    volumes:
      - ./minio:/etc/minio/
    entrypoint: >
      bash -c "
        sleep 5 &&
        mc alias set local http://minio:9000 minio minio123 &&
        mc mb local/dlh || true &&
        mc admin user add local lakehouseuser lakehousepass || true &&
        mc admin policy create local dlh-policy /etc/minio/dlh-policy.json || true &&
        mc admin policy attach local dlh-policy --user lakehouseuser &&
        mc anonymous set download local/dlh
      "
    networks:
      - dlh-network

  trino:
    hostname: trino
    container_name: trino
    image: 'trinodb/trino:455'
    ports:
      - '8080:8080'
    volumes:
      - ./catalog:/etc/trino/catalog
    networks:
      - dlh-network

volumes:
  minio-data:
    driver: local

networks:
  dlh-network:
    driver: bridge